# Generated by Django 4.1 on 2022-11-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='category',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('category', models.CharField(max_length=20)),
        #     ],
        # ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('subhead', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('le_contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='testLecture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('Lecturename', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('wallet_address', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=10)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=20)),
                ('re_contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture_id', models.ForeignKey(db_column='lecture_id', on_delete=django.db.models.deletion.CASCADE, related_name='Lecture', to='backend_api.lecture')),
            ],
        ),
    ]
