# Generated by Django 4.1 on 2022-11-28 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('headcount', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, default='no_image.gif', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('wallet_address', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=20)),
                ('re_contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture_id', models.ForeignKey(db_column='lecture_id', on_delete=django.db.models.deletion.CASCADE, related_name='Lecture', to='backend_api.lecture')),
            ],
        ),
    ]
