# Generated by Django 4.1.1 on 2022-11-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0002_titles_delete_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(name="titles",),
    ]
