# Generated by Django 4.1.3 on 2022-11-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_delete_testlecture_lecture_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
