# Generated by Django 4.1.3 on 2022-11-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0005_rename_le_contents_lecture_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
