# Generated by Django 4.1.3 on 2022-11-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0006_alter_lecture_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="lecture",
            name="thumbnail",
            field=models.ImageField(blank=True, default="no_image.gif", upload_to=""),
        ),
    ]
