# Generated by Django 4.1.3 on 2022-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend_api",
            "0007_remove_lecture_deleted_at_remove_lecture_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="userName",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
