<<<<<<< HEAD:project-koh/backend/backend_api/migrations/0001_initial.py
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD:project-koh/backend/backend_api/migrations/0009_initial.py
<<<<<<< HEAD:project-koh/backend/backend_api/migrations/0001_initial.py
# Generated by Django 4.1 on 2022-11-25 23:57
=======
# Generated by Django 4.1 on 2022-11-22 10:49
>>>>>>> d5374f01 (test: 병합 성공):project-koh/backend/backend_api/migrations/0009_initial.py
=======
# Generated by Django 4.1 on 2022-11-23 06:42
>>>>>>> 039a4455 (fix: api post 요청 충돌 해결):project-koh/backend/backend_api/migrations/0001_initial.py
=======
# Generated by Django 4.1 on 2022-11-23 06:42
>>>>>>> e51a34ef (fix: api post 요청 충돌 해결)
=======
# Generated by Django 4.1 on 2022-11-25 23:57
>>>>>>> b2886b69 (feat: 유저 정보 입력 페이지 추가)
=======
# Generated by Django 4.1 on 2022-11-22 10:49
>>>>>>> 81eae16f (test: 병합 성공):project-koh/backend/backend_api/migrations/0009_initial.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
<<<<<<< HEAD
<<<<<<< HEAD:project-koh/backend/backend_api/migrations/0001_initial.py
                ('content', models.TextField()),
                ('headcount', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, default='no_image.gif', upload_to='')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
=======
                ('le_contents', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD:project-koh/backend/backend_api/migrations/0001_initial.py
>>>>>>> d5374f01 (test: 병합 성공):project-koh/backend/backend_api/migrations/0009_initial.py
=======
                ('content', models.TextField()),
                ('headcount', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, default='no_image.gif', upload_to='')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> b2886b69 (feat: 유저 정보 입력 페이지 추가)
=======
>>>>>>> 81eae16f (test: 병합 성공):project-koh/backend/backend_api/migrations/0009_initial.py
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('wallet_address', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=10)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=20)),
                ('re_contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture_id', models.ForeignKey(db_column='lecture_id', on_delete=django.db.models.deletion.CASCADE, related_name='Lecture', to='backend_api.lecture')),
            ],
        ),
    ]
