# Generated by Django 4.1.3 on 2022-11-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0008_alter_lecture_content_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_public",
        ),
    ]
