# Generated by Django 4.1.3 on 2022-11-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0009_remove_lecture_is_public_remove_user_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
