# Generated by Django 4.1 on 2022-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '00011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
