# Generated by Django 4.1 on 2022-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_lecture_image_url_lecture_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
            ],
            options={
                'ordering': ['token'],
            },
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='headcount',
            new_name='count',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='default_image.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.ManyToManyField(to='backend_api.wallet'),
        ),
    ]
